META_WIDGET_LABEL = "_meta-15347"
KRITA_SAVE_IMAGE_NODE_TYPE = "KritaSaveImage-15347"
KRITA_DOCUMENT_DROPDOWN_LABEL = "document"

KRITA_INPUT_NODE_TYPES = []
KRITA_OUTPUT_NODE_TYPES = [KRITA_SAVE_IMAGE_NODE_TYPE]
